SELECT
    CURRENT_USER() AS USER_NAME,
    CURRENT_ROLE() AS ROLE_NAME,
    CURRENT_WAREHOUSE() AS WAREHOUSE_NAME,
    CURRENT_DATABASE() AS DATABASE_NAME,
    CURRENT_SCHEMA() AS SCHEMA_NAME;
    CREATE DATABASE CREDIT_RISK_MLOPS;
    CREATE DATABASE IF NOT EXISTS CREDIT_RISK_MLOPS;
    SHOW DATABASES
    CREATE SCHEMA CREDIT_RISK_MLOPS.RAW;

CREATE SCHEMA CREDIT_RISK_MLOPS.FEATURES;

CREATE SCHEMA CREDIT_RISK_MLOPS.ML;

CREATE SCHEMA CREDIT_RISK_MLOPS.INFERENCE;

CREATE SCHEMA CREDIT_RISK_MLOPS.REPORTING;
SHOW SCHEMAS IN DATABASE CREDIT_RISK_MLOPS;
SHOW SCHEMAS IN DATABASE CREDIT_RISK_MLOPS;
CREATE SCHEMA IF NOT EXISTS CREDIT_RISK_MLOPS.RAW;

CREATE SCHEMA IF NOT EXISTS CREDIT_RISK_MLOPS.FEATURES;

CREATE SCHEMA IF NOT EXISTS CREDIT_RISK_MLOPS.ML;

CREATE SCHEMA IF NOT EXISTS CREDIT_RISK_MLOPS.INFERENCE;
SHOW SCHEMAS IN DATABASE CREDIT_RISK_MLOPS;
CREATE WAREHOUSE IF NOT EXISTS CREDIT_RISK_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
    USE WAREHOUSE CREDIT_RISK_WH;
    SELECT CURRENT_WAREHOUSE();
    USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA RAW;
CREATE STAGE IF NOT EXISTS CREDIT_RISK_STAGE;
SHOW STAGES;
SHOW SCHEMAS IN DATABASE CREDIT_RISK_MLOPS;
USE DATABASE CREDIT_RISK_MLOPS;

USE SCHEMA RAW;

CREATE STAGE IF NOT EXISTS CREDIT_RISK_STAGE;
SHOW STAGES;
CREATE SCHEMA CREDIT_RISK_MLOPS.RAW;
SHOW SCHEMAS IN DATABASE CREDIT_RISK_MLOPS;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA RAW;
CREATE STAGE IF NOT EXISTS CREDIT_RISK_STAGE;
SHOW STAGES;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA RAW;

LIST @CREDIT_RISK_STAGE;
LIST @CREDIT_RISK_MLOPS.RAW.CREDIT_RISK_STAGE;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA RAW;

SELECT *
FROM CREDIT_DATA
LIMIT 10;
SELECT COUNT(*) AS TOTAL_ROWS
FROM CREDIT_DATA;
DESCRIBE TABLE CREDIT_DATA;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA RAW;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(LOAN_STATUS IS NULL) AS NULL_LOAN_STATUS,
    COUNT_IF(PERSON_AGE IS NULL) AS NULL_AGE,
    COUNT_IF(PERSON_INCOME IS NULL) AS NULL_INCOME,
    COUNT_IF(PERSON_HOME_OWN IS NULL) AS NULL_HOME_OWN,
    COUNT_IF(PERSON_EMP_LENG IS NULL) AS NULL_EMP_LENGTH,
    COUNT_IF(LOAN_INTENT IS NULL) AS NULL_LOAN_INTENT,
    COUNT_IF(LOAN_GRADE IS NULL) AS NULL_LOAN_GRADE,
    COUNT_IF(LOAN_AMNT IS NULL) AS NULL_LOAN_AMOUNT,
    COUNT_IF(LOAN_INT_RATE IS NULL) AS NULL_INTEREST_RATE,
    COUNT_IF(LOAN_PERCENT_INCOME IS NULL) AS NULL_LOAN_PERCENT_INCOME,
    COUNT_IF(CB_PERSON_DEFAULT IS NULL) AS NULL_PREVIOUS_DEFAULT,
    COUNT_IF(CB_PERSON_CRED_H IS NULL) AS NULL_CREDIT_HISTORY
FROM CREDIT_DATA;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA RAW;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(LOAN_STATUS IS NULL) AS NULL_LOAN_STATUS
FROM CREDIT_DATA;
SELECT
    LOAN_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM CREDIT_DATA
GROUP BY LOAN_STATUS
ORDER BY LOAN_STATUS;
SELECT *
FROM CREDIT_DATA
LIMIT 5;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA RAW;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PERSON_AGE IS NULL) AS NULL_AGE,
    COUNT_IF(PERSON_INCOME IS NULL) AS NULL_INCOME,
    COUNT_IF(PERSON_HOME_OWNERSHIP IS NULL) AS NULL_HOME_OWNERSHIP,
    COUNT_IF(PERSON_EMP_LENGTH IS NULL) AS NULL_EMP_LENGTH,
    COUNT_IF(LOAN_INTENT IS NULL) AS NULL_LOAN_INTENT,
    COUNT_IF(LOAN_GRADE IS NULL) AS NULL_LOAN_GRADE,
    COUNT_IF(LOAN_AMNT IS NULL) AS NULL_LOAN_AMOUNT,
    COUNT_IF(LOAN_INT_RATE IS NULL) AS NULL_INTEREST_RATE,
    COUNT_IF(LOAN_STATUS IS NULL) AS NULL_LOAN_STATUS,
    COUNT_IF(LOAN_PERCENT_INCOME IS NULL) AS NULL_PERCENT_INCOME,
    COUNT_IF(CB_PERSON_DEFAULT_ON_FILE IS NULL) AS NULL_DEFAULT_HISTORY,
    COUNT_IF(CB_PERSON_CRED_HIST_LENGTH IS NULL) AS NULL_CREDIT_HISTORY
FROM CREDIT_DATA;
SELECT
    LOAN_STATUS,
    COUNT(*) AS RECORD_COUNT,
    ROUND(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),
        2
    ) AS PERCENTAGE
FROM CREDIT_DATA
GROUP BY LOAN_STATUS
ORDER BY LOAN_STATUS;
SELECT
    MIN(PERSON_EMP_LENGTH) AS MIN_EMP_LENGTH,
    MAX(PERSON_EMP_LENGTH) AS MAX_EMP_LENGTH,
    COUNT_IF(PERSON_EMP_LENGTH > 50) AS EMP_LENGTH_OVER_50
FROM CREDIT_DATA;
SELECT
    PERSON_AGE,
    PERSON_INCOME,
    PERSON_HOME_OWNERSHIP,
    PERSON_EMP_LENGTH,
    LOAN_INTENT,
    LOAN_GRADE,
    LOAN_AMNT,
    LOAN_INT_RATE,
    LOAN_STATUS,
    LOAN_PERCENT_INCOME,
    CB_PERSON_DEFAULT_ON_FILE,
    CB_PERSON_CRED_HIST_LENGTH
FROM CREDIT_DATA
WHERE PERSON_EMP_LENGTH > 50
ORDER BY PERSON_EMP_LENGTH DESC;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN AS
SELECT
    PERSON_AGE,
    PERSON_INCOME,
    PERSON_HOME_OWNERSHIP,
    CASE
        WHEN PERSON_EMP_LENGTH > 50 THEN NULL
        ELSE PERSON_EMP_LENGTH
    END AS PERSON_EMP_LENGTH,
    LOAN_INTENT,
    LOAN_GRADE,
    LOAN_AMNT,
    LOAN_INT_RATE,
    LOAN_STATUS,
    LOAN_PERCENT_INCOME,
    CB_PERSON_DEFAULT_ON_FILE,
    CB_PERSON_CRED_HIST_LENGTH
FROM CREDIT_RISK_MLOPS.RAW.CREDIT_DATA;
USE DATABASE CREDIT_RISK_MLOPS;

CREATE SCHEMA IF NOT EXISTS FEATURES;
SHOW SCHEMAS IN DATABASE CREDIT_RISK_MLOPS;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN AS
SELECT
    PERSON_AGE,
    PERSON_INCOME,
    PERSON_HOME_OWNERSHIP,
    CASE
        WHEN PERSON_EMP_LENGTH > 50 THEN NULL
        ELSE PERSON_EMP_LENGTH
    END AS PERSON_EMP_LENGTH,
    LOAN_INTENT,
    LOAN_GRADE,
    LOAN_AMNT,
    LOAN_INT_RATE,
    LOAN_STATUS,
    LOAN_PERCENT_INCOME,
    CB_PERSON_DEFAULT_ON_FILE,
    CB_PERSON_CRED_HIST_LENGTH
FROM CREDIT_RISK_MLOPS.RAW.CREDIT_DATA;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PERSON_EMP_LENGTH IS NULL) AS NULL_EMP_LENGTH,
    MAX(PERSON_EMP_LENGTH) AS MAX_EMP_LENGTH
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA FEATURES;

SELECT
    MIN(PERSON_AGE) AS MIN_AGE,
    MAX(PERSON_AGE) AS MAX_AGE,
    MIN(PERSON_INCOME) AS MIN_INCOME,
    MAX(PERSON_INCOME) AS MAX_INCOME,
    MIN(PERSON_EMP_LENGTH) AS MIN_EMP_LENGTH,
    MAX(PERSON_EMP_LENGTH) AS MAX_EMP_LENGTH,
    MIN(LOAN_AMNT) AS MIN_LOAN_AMOUNT,
    MAX(LOAN_AMNT) AS MAX_LOAN_AMOUNT,
    MIN(LOAN_INT_RATE) AS MIN_INTEREST_RATE,
    MAX(LOAN_INT_RATE) AS MAX_INTEREST_RATE,
    MIN(LOAN_PERCENT_INCOME) AS MIN_LOAN_PERCENT_INCOME,
    MAX(LOAN_PERCENT_INCOME) AS MAX_LOAN_PERCENT_INCOME,
    MIN(CB_PERSON_CRED_HIST_LENGTH) AS MIN_CREDIT_HISTORY,
    MAX(CB_PERSON_CRED_HIST_LENGTH) AS MAX_CREDIT_HISTORY
FROM CREDIT_CLEAN;
SELECT 'HOME_OWNERSHIP' AS FEATURE, PERSON_HOME_OWNERSHIP AS VALUE, COUNT(*) AS RECORD_COUNT
FROM CREDIT_CLEAN
GROUP BY PERSON_HOME_OWNERSHIP

UNION ALL

SELECT 'LOAN_INTENT', LOAN_INTENT, COUNT(*)
FROM CREDIT_CLEAN
GROUP BY LOAN_INTENT

UNION ALL

SELECT 'LOAN_GRADE', LOAN_GRADE, COUNT(*)
FROM CREDIT_CLEAN
GROUP BY LOAN_GRADE

ORDER BY FEATURE, VALUE;
SELECT
    PERSON_AGE,
    PERSON_INCOME,
    PERSON_HOME_OWNERSHIP,
    PERSON_EMP_LENGTH,
    LOAN_INTENT,
    LOAN_GRADE,
    LOAN_AMNT,
    LOAN_INT_RATE,
    LOAN_STATUS,
    LOAN_PERCENT_INCOME,
    CB_PERSON_DEFAULT_ON_FILE,
    CB_PERSON_CRED_HIST_LENGTH
FROM CREDIT_CLEAN
WHERE PERSON_AGE > 100
ORDER BY PERSON_AGE DESC;
SELECT COUNT(*) AS AGE_OVER_100
FROM CREDIT_CLEAN
WHERE PERSON_AGE > 100;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN AS
SELECT
    CASE
        WHEN PERSON_AGE > 100 THEN NULL
        ELSE PERSON_AGE
    END AS PERSON_AGE,
    PERSON_INCOME,
    PERSON_HOME_OWNERSHIP,
    PERSON_EMP_LENGTH,
    LOAN_INTENT,
    LOAN_GRADE,
    LOAN_AMNT,
    LOAN_INT_RATE,
    LOAN_STATUS,
    LOAN_PERCENT_INCOME,
    CB_PERSON_DEFAULT_ON_FILE,
    CB_PERSON_CRED_HIST_LENGTH
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PERSON_AGE IS NULL) AS NULL_AGE,
    MIN(PERSON_AGE) AS MIN_AGE,
    MAX(PERSON_AGE) AS MAX_AGE
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PERSON_AGE IS NULL) AS NULL_AGE,
    COUNT_IF(PERSON_INCOME IS NULL) AS NULL_INCOME,
    COUNT_IF(PERSON_HOME_OWNERSHIP IS NULL) AS NULL_HOME_OWNERSHIP,
    COUNT_IF(PERSON_EMP_LENGTH IS NULL) AS NULL_EMP_LENGTH,
    COUNT_IF(LOAN_INTENT IS NULL) AS NULL_LOAN_INTENT,
    COUNT_IF(LOAN_GRADE IS NULL) AS NULL_LOAN_GRADE,
    COUNT_IF(LOAN_AMNT IS NULL) AS NULL_LOAN_AMOUNT,
    COUNT_IF(LOAN_INT_RATE IS NULL) AS NULL_INTEREST_RATE,
    COUNT_IF(LOAN_STATUS IS NULL) AS NULL_LOAN_STATUS,
    COUNT_IF(LOAN_PERCENT_INCOME IS NULL) AS NULL_PERCENT_INCOME,
    COUNT_IF(CB_PERSON_DEFAULT_ON_FILE IS NULL) AS NULL_DEFAULT_HISTORY,
    COUNT_IF(CB_PERSON_CRED_HIST_LENGTH IS NULL) AS NULL_CREDIT_HISTORY
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN;
SELECT
    LOAN_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN
GROUP BY LOAN_STATUS
ORDER BY LOAN_STATUS;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PERSON_AGE IS NULL) AS NULL_AGE,
    COUNT_IF(PERSON_INCOME IS NULL) AS NULL_INCOME,
    COUNT_IF(PERSON_HOME_OWNERSHIP IS NULL) AS NULL_HOME_OWNERSHIP,
    COUNT_IF(PERSON_EMP_LENGTH IS NULL) AS NULL_EMP_LENGTH,
    COUNT_IF(LOAN_INTENT IS NULL) AS NULL_LOAN_INTENT,
    COUNT_IF(LOAN_GRADE IS NULL) AS NULL_LOAN_GRADE,
    COUNT_IF(LOAN_AMNT IS NULL) AS NULL_LOAN_AMOUNT,
    COUNT_IF(LOAN_INT_RATE IS NULL) AS NULL_INTEREST_RATE,
    COUNT_IF(LOAN_STATUS IS NULL) AS NULL_LOAN_STATUS,
    COUNT_IF(LOAN_PERCENT_INCOME IS NULL) AS NULL_PERCENT_INCOME,
    COUNT_IF(CB_PERSON_DEFAULT_ON_FILE IS NULL) AS NULL_DEFAULT_HISTORY,
    COUNT_IF(CB_PERSON_CRED_HIST_LENGTH IS NULL) AS NULL_CREDIT_HISTORY
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.FEATURES.CREDIT_FEATURES AS
SELECT
    PERSON_AGE,
    PERSON_INCOME,
    PERSON_HOME_OWNERSHIP,
    PERSON_EMP_LENGTH,
    LOAN_INTENT,
    LOAN_GRADE,
    LOAN_AMNT,
    LOAN_INT_RATE,
    LOAN_PERCENT_INCOME,
    CB_PERSON_DEFAULT_ON_FILE,
    CB_PERSON_CRED_HIST_LENGTH,
    LOAN_STATUS,

    -- Derived financial features
    LOAN_AMNT / NULLIF(PERSON_INCOME, 0) AS LOAN_TO_INCOME,

    PERSON_INCOME / NULLIF(LOAN_AMNT, 0) AS INCOME_PER_LOAN,

    -- Credit history relative to age
    CB_PERSON_CRED_HIST_LENGTH / NULLIF(PERSON_AGE, 0)
        AS CREDIT_HISTORY_TO_AGE,

    -- Employment relative to age
    PERSON_EMP_LENGTH / NULLIF(PERSON_AGE, 0)
        AS EMPLOYMENT_TO_AGE,

    -- Previous default indicator
    IFF(CB_PERSON_DEFAULT_ON_FILE = TRUE, 1, 0)
        AS HAS_PREVIOUS_DEFAULT

FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_CLEAN;
SELECT *
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_FEATURES
LIMIT 10;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(LOAN_TO_INCOME IS NULL) AS NULL_LOAN_TO_INCOME,
    COUNT_IF(INCOME_PER_LOAN IS NULL) AS NULL_INCOME_PER_LOAN,
    COUNT_IF(CREDIT_HISTORY_TO_AGE IS NULL) AS NULL_CREDIT_HISTORY_RATIO,
    COUNT_IF(EMPLOYMENT_TO_AGE IS NULL) AS NULL_EMPLOYMENT_RATIO
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_FEATURES;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.FEATURES.CREDIT_MODEL_DATA AS
SELECT
    COALESCE(
        PERSON_AGE,
        MEDIAN(PERSON_AGE) OVER ()
    ) AS PERSON_AGE,

    PERSON_INCOME,

    PERSON_HOME_OWNERSHIP,

    COALESCE(
        PERSON_EMP_LENGTH,
        MEDIAN(PERSON_EMP_LENGTH) OVER ()
    ) AS PERSON_EMP_LENGTH,

    LOAN_INTENT,
    LOAN_GRADE,
    LOAN_AMNT,

    COALESCE(
        LOAN_INT_RATE,
        MEDIAN(LOAN_INT_RATE) OVER ()
    ) AS LOAN_INT_RATE,

    LOAN_PERCENT_INCOME,
    CB_PERSON_DEFAULT_ON_FILE,
    CB_PERSON_CRED_HIST_LENGTH,
    LOAN_STATUS,

    LOAN_TO_INCOME,
    INCOME_PER_LOAN,
    CREDIT_HISTORY_TO_AGE,
    EMPLOYMENT_TO_AGE,
    HAS_PREVIOUS_DEFAULT

FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_FEATURES;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PERSON_AGE IS NULL) AS NULL_AGE,
    COUNT_IF(PERSON_EMP_LENGTH IS NULL) AS NULL_EMP_LENGTH,
    COUNT_IF(LOAN_INT_RATE IS NULL) AS NULL_INTEREST_RATE
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_MODEL_DATA;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.FEATURES.CREDIT_MODEL_SPLIT AS
SELECT
    *,
    UNIFORM(0::FLOAT, 1::FLOAT, RANDOM(42)) AS SPLIT_RANDOM
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_MODEL_DATA;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.ML.TRAIN_DATA AS
SELECT *
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_MODEL_SPLIT
WHERE SPLIT_RANDOM < 0.80;
CREATE SCHEMA IF NOT EXISTS CREDIT_RISK_MLOPS.ML;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.ML.TRAIN_DATA AS
SELECT *
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_MODEL_SPLIT
WHERE SPLIT_RANDOM < 0.80;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.ML.TEST_DATA AS
SELECT *
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_MODEL_SPLIT
WHERE SPLIT_RANDOM >= 0.80;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.ML.TEST_DATA AS
SELECT *
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_MODEL_SPLIT
WHERE SPLIT_RANDOM >= 0.80;
SELECT
    'TRAIN' AS DATASET,
    COUNT(*) AS ROW_COUNT,
    ROUND(100 * AVG(LOAN_STATUS), 2) AS DEFAULT_RATE
FROM CREDIT_RISK_MLOPS.ML.TRAIN_DATA

UNION ALL

SELECT
    'TEST',
    COUNT(*),
    ROUND(100 * AVG(LOAN_STATUS), 2)
FROM CREDIT_RISK_MLOPS.ML.TEST_DATA;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.ML.TRAIN_MODEL AS
SELECT
    PERSON_AGE,
    PERSON_INCOME,
    PERSON_EMP_LENGTH,
    LOAN_AMNT,
    LOAN_INT_RATE,
    LOAN_PERCENT_INCOME,
    CB_PERSON_CRED_HIST_LENGTH,

    LOAN_TO_INCOME,
    INCOME_PER_LOAN,
    CREDIT_HISTORY_TO_AGE,
    EMPLOYMENT_TO_AGE,
    HAS_PREVIOUS_DEFAULT,

    -- Home ownership
    IFF(PERSON_HOME_OWNERSHIP = 'MORTGAGE', 1, 0) AS HOME_MORTGAGE,
    IFF(PERSON_HOME_OWNERSHIP = 'OWN', 1, 0) AS HOME_OWN,
    IFF(PERSON_HOME_OWNERSHIP = 'RENT', 1, 0) AS HOME_RENT,
    IFF(PERSON_HOME_OWNERSHIP = 'OTHER', 1, 0) AS HOME_OTHER,

    -- Loan intent
    IFF(LOAN_INTENT = 'DEBTCONSOLIDATION', 1, 0) AS INTENT_DEBTCONSOLIDATION,
    IFF(LOAN_INTENT = 'EDUCATION', 1, 0) AS INTENT_EDUCATION,
    IFF(LOAN_INTENT = 'HOMEIMPROVEMENT', 1, 0) AS INTENT_HOMEIMPROVEMENT,
    IFF(LOAN_INTENT = 'MEDICAL', 1, 0) AS INTENT_MEDICAL,
    IFF(LOAN_INTENT = 'PERSONAL', 1, 0) AS INTENT_PERSONAL,
    IFF(LOAN_INTENT = 'VENTURE', 1, 0) AS INTENT_VENTURE,

    -- Loan grade
    IFF(LOAN_GRADE = 'A', 1, 0) AS GRADE_A,
    IFF(LOAN_GRADE = 'B', 1, 0) AS GRADE_B,
    IFF(LOAN_GRADE = 'C', 1, 0) AS GRADE_C,
    IFF(LOAN_GRADE = 'D', 1, 0) AS GRADE_D,
    IFF(LOAN_GRADE = 'E', 1, 0) AS GRADE_E,
    IFF(LOAN_GRADE = 'F', 1, 0) AS GRADE_F,
    IFF(LOAN_GRADE = 'G', 1, 0) AS GRADE_G,

    LOAN_STATUS
FROM CREDIT_RISK_MLOPS.ML.TRAIN_DATA;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.ML.TEST_MODEL AS
SELECT
    PERSON_AGE,
    PERSON_INCOME,
    PERSON_EMP_LENGTH,
    LOAN_AMNT,
    LOAN_INT_RATE,
    LOAN_PERCENT_INCOME,
    CB_PERSON_CRED_HIST_LENGTH,

    LOAN_TO_INCOME,
    INCOME_PER_LOAN,
    CREDIT_HISTORY_TO_AGE,
    EMPLOYMENT_TO_AGE,
    HAS_PREVIOUS_DEFAULT,

    IFF(PERSON_HOME_OWNERSHIP = 'MORTGAGE', 1, 0) AS HOME_MORTGAGE,
    IFF(PERSON_HOME_OWNERSHIP = 'OWN', 1, 0) AS HOME_OWN,
    IFF(PERSON_HOME_OWNERSHIP = 'RENT', 1, 0) AS HOME_RENT,
    IFF(PERSON_HOME_OWNERSHIP = 'OTHER', 1, 0) AS HOME_OTHER,

    IFF(LOAN_INTENT = 'DEBTCONSOLIDATION', 1, 0) AS INTENT_DEBTCONSOLIDATION,
    IFF(LOAN_INTENT = 'EDUCATION', 1, 0) AS INTENT_EDUCATION,
    IFF(LOAN_INTENT = 'HOMEIMPROVEMENT', 1, 0) AS INTENT_HOMEIMPROVEMENT,
    IFF(LOAN_INTENT = 'MEDICAL', 1, 0) AS INTENT_MEDICAL,
    IFF(LOAN_INTENT = 'PERSONAL', 1, 0) AS INTENT_PERSONAL,
    IFF(LOAN_INTENT = 'VENTURE', 1, 0) AS INTENT_VENTURE,

    IFF(LOAN_GRADE = 'A', 1, 0) AS GRADE_A,
    IFF(LOAN_GRADE = 'B', 1, 0) AS GRADE_B,
    IFF(LOAN_GRADE = 'C', 1, 0) AS GRADE_C,
    IFF(LOAN_GRADE = 'D', 1, 0) AS GRADE_D,
    IFF(LOAN_GRADE = 'E', 1, 0) AS GRADE_E,
    IFF(LOAN_GRADE = 'F', 1, 0) AS GRADE_F,
    IFF(LOAN_GRADE = 'G', 1, 0) AS GRADE_G,

    LOAN_STATUS
FROM CREDIT_RISK_MLOPS.ML.TEST_DATA;
SELECT COUNT(*) AS ROW_COUNT
FROM CREDIT_RISK_MLOPS.ML.TRAIN_MODEL;
SELECT COUNT(*) AS ROW_COUNT
FROM CREDIT_RISK_MLOPS.ML.TEST_MODEL;
SELECT CURRENT_VERSION();
SELECT SYSTEM$TYPEOF(
    SNOWFLAKE.CORTEX.COMPLETE(
        'claude-3-5-sonnet',
        'Reply with the word OK'
    )
) AS CORTEX_CHECK;
from snowflake.snowpark import Session
from snowflake.snowpark.functions import col

print("Snowpark is available")
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA ML;
CREATE OR REPLACE VIEW CREDIT_RISK_MLOPS.ML.CREDIT_TRAINING_VIEW AS
SELECT
    PERSON_AGE,
    PERSON_INCOME,
    PERSON_EMP_LENGTH,
    LOAN_AMNT,
    LOAN_INT_RATE,
    LOAN_PERCENT_INCOME,
    CB_PERSON_CRED_HIST_LENGTH,
    LOAN_TO_INCOME,
    INCOME_PER_LOAN,
    CREDIT_HISTORY_TO_AGE,
    EMPLOYMENT_TO_AGE,
    HAS_PREVIOUS_DEFAULT,

    HOME_MORTGAGE,
    HOME_OWN,
    HOME_RENT,
    HOME_OTHER,

    INTENT_DEBTCONSOLIDATION,
    INTENT_EDUCATION,
    INTENT_HOMEIMPROVEMENT,
    INTENT_MEDICAL,
    INTENT_PERSONAL,
    INTENT_VENTURE,

    GRADE_A,
    GRADE_B,
    GRADE_C,
    GRADE_D,
    GRADE_E,
    GRADE_F,
    GRADE_G,

    LOAN_STATUS
FROM CREDIT_RISK_MLOPS.ML.TRAIN_MODEL;
SELECT *
FROM CREDIT_RISK_MLOPS.ML.CREDIT_TRAINING_VIEW
LIMIT 10;
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION
    CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE
(
    INPUT_DATA => SYSTEM$REFERENCE(
        'VIEW',
        'CREDIT_RISK_MLOPS.ML.CREDIT_TRAINING_VIEW'
    ),
    TARGET_COLNAME => 'LOAN_STATUS',
    CONFIG_OBJECT => {
        'evaluate': TRUE
    }
);
SHOW SNOWFLAKE.ML.CLASSIFICATION
IN SCHEMA CREDIT_RISK_MLOPS.ML;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.ML.TEST_PREDICTIONS AS
SELECT
    t.*,
    p.*
FROM CREDIT_RISK_MLOPS.ML.TEST_MODEL t,
    TABLE(
        CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!PREDICT(
            INPUT_DATA => TABLE(
                SELECT
                    PERSON_AGE,
                    PERSON_INCOME,
                    PERSON_EMP_LENGTH,
                    LOAN_AMNT,
                    LOAN_INT_RATE,
                    LOAN_PERCENT_INCOME,
                    CB_PERSON_CRED_HIST_LENGTH,
                    LOAN_TO_INCOME,
                    INCOME_PER_LOAN,
                    CREDIT_HISTORY_TO_AGE,
                    EMPLOYMENT_TO_AGE,
                    HAS_PREVIOUS_DEFAULT,
                    HOME_MORTGAGE,
                    HOME_OWN,
                    HOME_RENT,
                    HOME_OTHER,
                    INTENT_DEBTCONSOLIDATION,
                    INTENT_EDUCATION,
                    INTENT_HOMEIMPROVEMENT,
                    INTENT_MEDICAL,
                    INTENT_PERSONAL,
                    INTENT_VENTURE,
                    GRADE_A,
                    GRADE_B,
                    GRADE_C,
                    GRADE_D,
                    GRADE_E,
                    GRADE_F,
                    GRADE_G
                FROM CREDIT_RISK_MLOPS.ML.TEST_MODEL
            )
        )
    ) p;
    SELECT
    *,
    CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!PREDICT(
        INPUT_DATA => {*}
    ) AS PREDICTION
FROM CREDIT_RISK_MLOPS.ML.TEST_MODEL
LIMIT 10;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.ML.TEST_PREDICTIONS AS
SELECT
    t.*,
    p.PREDICTION
FROM CREDIT_RISK_MLOPS.ML.TEST_MODEL t,
LATERAL (
    SELECT
        CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!PREDICT(
            INPUT_DATA => OBJECT_CONSTRUCT(
                'PERSON_AGE', t.PERSON_AGE,
                'PERSON_INCOME', t.PERSON_INCOME,
                'PERSON_EMP_LENGTH', t.PERSON_EMP_LENGTH,
                'LOAN_AMNT', t.LOAN_AMNT,
                'LOAN_INT_RATE', t.LOAN_INT_RATE,
                'LOAN_PERCENT_INCOME', t.LOAN_PERCENT_INCOME,
                'CB_PERSON_CRED_HIST_LENGTH', t.CB_PERSON_CRED_HIST_LENGTH,
                'LOAN_TO_INCOME', t.LOAN_TO_INCOME,
                'INCOME_PER_LOAN', t.INCOME_PER_LOAN,
                'CREDIT_HISTORY_TO_AGE', t.CREDIT_HISTORY_TO_AGE,
                'EMPLOYMENT_TO_AGE', t.EMPLOYMENT_TO_AGE,
                'HAS_PREVIOUS_DEFAULT', t.HAS_PREVIOUS_DEFAULT,
                'HOME_MORTGAGE', t.HOME_MORTGAGE,
                'HOME_OWN', t.HOME_OWN,
                'HOME_RENT', t.HOME_RENT,
                'HOME_OTHER', t.HOME_OTHER,
                'INTENT_DEBTCONSOLIDATION', t.INTENT_DEBTCONSOLIDATION,
                'INTENT_EDUCATION', t.INTENT_EDUCATION,
                'INTENT_HOMEIMPROVEMENT', t.INTENT_HOMEIMPROVEMENT,
                'INTENT_MEDICAL', t.INTENT_MEDICAL,
                'INTENT_PERSONAL', t.INTENT_PERSONAL,
                'INTENT_VENTURE', t.INTENT_VENTURE,
                'GRADE_A', t.GRADE_A,
                'GRADE_B', t.GRADE_B,
                'GRADE_C', t.GRADE_C,
                'GRADE_D', t.GRADE_D,
                'GRADE_E', t.GRADE_E,
                'GRADE_F', t.GRADE_F,
                'GRADE_G', t.GRADE_G
            )
        ) AS PREDICTION
) p;
SELECT *
FROM CREDIT_RISK_MLOPS.ML.TEST_PREDICTIONS
LIMIT 10;
CALL CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!SHOW_GLOBAL_EVALUATION_METRICS();
CALL CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!SHOW_THRESHOLD_METRICS();
CALL CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!SHOW_THRESHOLD_METRICS();
CALL CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!SHOW_CONFUSION_MATRIX();
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA ML;
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION
    CREDIT_RISK_MLOPS.ML.CREDIT_RISK_SECOND
(
    INPUT_DATA => SYSTEM$REFERENCE(
        'VIEW',
        'CREDIT_RISK_MLOPS.ML.CREDIT_TRAINING_VIEW'
    ),
    TARGET_COLNAME => 'LOAN_STATUS',
    CONFIG_OBJECT => {
        'evaluate': TRUE
    }
);
SHOW SNOWFLAKE.ML.CLASSIFICATION
IN SCHEMA CREDIT_RISK_MLOPS.ML;
CALL CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!SHOW_GLOBAL_EVALUATION_METRICS();
CALL CREDIT_RISK_MLOPS.ML.CREDIT_RISK_SECOND!SHOW_GLOBAL_EVALUATION_METRICS();
SHOW SNOWFLAKE.ML.CLASSIFICATION
IN SCHEMA CREDIT_RISK_MLOPS.ML;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.ML.MODEL_SELECTION AS
SELECT
    'CREDIT_RISK_BASELINE' AS SELECTED_MODEL,
    'SNOWFLAKE.ML.CLASSIFICATION' AS MODEL_TYPE,
    0.9553878904 AS ROC_AUC,
    0.9432925818 AS WEIGHTED_PRECISION,
    0.9402007857 AS WEIGHTED_RECALL,
    0.9369269504 AS WEIGHTED_F1,
    0.1784136403 AS LOG_LOSS,
    'Selected as production candidate; second model produced identical evaluation metrics.' AS SELECTION_NOTE;
    SELECT *
FROM CREDIT_RISK_MLOPS.ML.MODEL_SELECTION;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_PREDICTIONS AS
SELECT
    t.*,
    p.PREDICTION
FROM CREDIT_RISK_MLOPS.ML.TEST_MODEL t,
LATERAL (
    SELECT
        CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!PREDICT(
            INPUT_DATA => OBJECT_CONSTRUCT(
                'PERSON_AGE', t.PERSON_AGE,
                'PERSON_INCOME', t.PERSON_INCOME,
                'PERSON_EMP_LENGTH', t.PERSON_EMP_LENGTH,
                'LOAN_AMNT', t.LOAN_AMNT,
                'LOAN_INT_RATE', t.LOAN_INT_RATE,
                'LOAN_PERCENT_INCOME', t.LOAN_PERCENT_INCOME,
                'CB_PERSON_CRED_HIST_LENGTH', t.CB_PERSON_CRED_HIST_LENGTH,
                'LOAN_TO_INCOME', t.LOAN_TO_INCOME,
                'INCOME_PER_LOAN', t.INCOME_PER_LOAN,
                'CREDIT_HISTORY_TO_AGE', t.CREDIT_HISTORY_TO_AGE,
                'EMPLOYMENT_TO_AGE', t.EMPLOYMENT_TO_AGE,
                'HAS_PREVIOUS_DEFAULT', t.HAS_PREVIOUS_DEFAULT,
                'HOME_MORTGAGE', t.HOME_MORTGAGE,
                'HOME_OWN', t.HOME_OWN,
                'HOME_RENT', t.HOME_RENT,
                'HOME_OTHER', t.HOME_OTHER,
                'INTENT_DEBTCONSOLIDATION', t.INTENT_DEBTCONSOLIDATION,
                'INTENT_EDUCATION', t.INTENT_EDUCATION,
                'INTENT_HOMEIMPROVEMENT', t.INTENT_HOMEIMPROVEMENT,
                'INTENT_MEDICAL', t.INTENT_MEDICAL,
                'INTENT_PERSONAL', t.INTENT_PERSONAL,
                'INTENT_VENTURE', t.INTENT_VENTURE,
                'GRADE_A', t.GRADE_A,
                'GRADE_B', t.GRADE_B,
                'GRADE_C', t.GRADE_C,
                'GRADE_D', t.GRADE_D,
                'GRADE_E', t.GRADE_E,
                'GRADE_F', t.GRADE_F,
                'GRADE_G', t.GRADE_G
            )
        ) AS PREDICTION
) p;
SELECT *
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_PREDICTIONS
LIMIT 10;
SELECT COUNT(*) AS PRODUCTION_ROWS
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_PREDICTIONS;
SELECT COUNT(*) AS TEST_MODEL_ROWS
FROM CREDIT_RISK_MLOPS.ML.TEST_MODEL;
SELECT COUNT(*) AS PRODUCTION_ROWS
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_PREDICTIONS;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_RISK AS
SELECT
    *,
    TRY_TO_DOUBLE(PREDICTION:probability:"1"::STRING) AS PD,
    CASE
        WHEN TRY_TO_DOUBLE(PREDICTION:probability:"1"::STRING) < 0.10
            THEN 'LOW'
        WHEN TRY_TO_DOUBLE(PREDICTION:probability:"1"::STRING) < 0.30
            THEN 'MEDIUM'
        WHEN TRY_TO_DOUBLE(PREDICTION:probability:"1"::STRING) < 0.50
            THEN 'HIGH'
        ELSE 'VERY_HIGH'
    END AS RISK_BAND
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_PREDICTIONS;
SELECT
    RISK_BAND,
    COUNT(*) AS CUSTOMER_COUNT,
    ROUND(AVG(PD), 4) AS AVG_PD
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_RISK
GROUP BY RISK_BAND
ORDER BY
    CASE RISK_BAND
        WHEN 'LOW' THEN 1
        WHEN 'MEDIUM' THEN 2
        WHEN 'HIGH' THEN 3
        WHEN 'VERY_HIGH' THEN 4
    END;
    CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.REPORTING.RISK_SUMMARY AS
SELECT
    RISK_BAND,
    COUNT(*) AS CUSTOMER_COUNT,
    ROUND(AVG(PD), 4) AS AVG_PD,
    ROUND(MIN(PD), 4) AS MIN_PD,
    ROUND(MAX(PD), 4) AS MAX_PD
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_RISK
GROUP BY RISK_BAND
ORDER BY
    CASE RISK_BAND
        WHEN 'LOW' THEN 1
        WHEN 'MEDIUM' THEN 2
        WHEN 'HIGH' THEN 3
        WHEN 'VERY_HIGH' THEN 4
    END;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.REPORTING.MODEL_SUMMARY AS
SELECT
    SELECTED_MODEL,
    MODEL_TYPE,
    ROC_AUC,
    WEIGHTED_PRECISION,
    WEIGHTED_RECALL,
    WEIGHTED_F1,
    LOG_LOSS,
    SELECTION_NOTE
FROM CREDIT_RISK_MLOPS.ML.MODEL_SELECTION;
SELECT *
FROM CREDIT_RISK_MLOPS.REPORTING.RISK_SUMMARY;
SELECT *
FROM CREDIT_RISK_MLOPS.REPORTING.MODEL_SUMMARY;
SELECT *
FROM CREDIT_RISK_MLOPS.REPORTING.RISK_SUMMARY;
SELECT
    RISK_BAND,
    CUSTOMER_COUNT
FROM CREDIT_RISK_MLOPS.REPORTING.RISK_SUMMARY
ORDER BY
    CASE RISK_BAND
        WHEN 'LOW' THEN 1
        WHEN 'MEDIUM' THEN 2
        WHEN 'HIGH' THEN 3
        WHEN 'VERY_HIGH' THEN 4
    END;

SELECT
    RISK_BAND,
    AVG_PD
FROM CREDIT_RISK_MLOPS.REPORTING.RISK_SUMMARY
ORDER BY
    CASE RISK_BAND
        WHEN 'LOW' THEN 1
        WHEN 'MEDIUM' THEN 2
        WHEN 'HIGH' THEN 3
        WHEN 'VERY_HIGH' THEN 4
    END;
SELECT
    SELECTED_MODEL,
    ROC_AUC,
    WEIGHTED_PRECISION,
    WEIGHTED_RECALL,
    WEIGHTED_F1,
    LOG_LOSS
FROM CREDIT_RISK_MLOPS.REPORTING.MODEL_SUMMARY;
USE DATABASE CREDIT_RISK_MLOPS;
USE SCHEMA INFERENCE;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PERSON_AGE IS NULL) AS MISSING_PERSON_AGE,
    COUNT_IF(PERSON_INCOME IS NULL) AS MISSING_PERSON_INCOME,
    COUNT_IF(PERSON_EMP_LENGTH IS NULL) AS MISSING_EMP_LENGTH,
    COUNT_IF(LOAN_AMNT IS NULL) AS MISSING_LOAN_AMNT,
    COUNT_IF(LOAN_INT_RATE IS NULL) AS MISSING_INTEREST_RATE,
    COUNT_IF(LOAN_PERCENT_INCOME IS NULL) AS MISSING_LOAN_PERCENT_INCOME,
    COUNT_IF(LOAN_TO_INCOME IS NULL) AS MISSING_LOAN_TO_INCOME,
    COUNT_IF(INCOME_PER_LOAN IS NULL) AS MISSING_INCOME_PER_LOAN,
    COUNT_IF(CREDIT_HISTORY_TO_AGE IS NULL) AS MISSING_CREDIT_HISTORY_RATIO,
    COUNT_IF(EMPLOYMENT_TO_AGE IS NULL) AS MISSING_EMPLOYMENT_RATIO,
    COUNT_IF(PD IS NULL) AS MISSING_PD
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_RISK;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.REPORTING.DATA_QUALITY_MONITOR AS
SELECT
    CURRENT_TIMESTAMP() AS CHECK_TIME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PERSON_AGE IS NULL) AS MISSING_PERSON_AGE,
    COUNT_IF(PERSON_INCOME IS NULL) AS MISSING_PERSON_INCOME,
    COUNT_IF(PERSON_EMP_LENGTH IS NULL) AS MISSING_EMP_LENGTH,
    COUNT_IF(LOAN_AMNT IS NULL) AS MISSING_LOAN_AMNT,
    COUNT_IF(LOAN_INT_RATE IS NULL) AS MISSING_INTEREST_RATE,
    COUNT_IF(LOAN_PERCENT_INCOME IS NULL) AS MISSING_LOAN_PERCENT_INCOME,
    COUNT_IF(LOAN_TO_INCOME IS NULL) AS MISSING_LOAN_TO_INCOME,
    COUNT_IF(INCOME_PER_LOAN IS NULL) AS MISSING_INCOME_PER_LOAN,
    COUNT_IF(CREDIT_HISTORY_TO_AGE IS NULL) AS MISSING_CREDIT_HISTORY_RATIO,
    COUNT_IF(EMPLOYMENT_TO_AGE IS NULL) AS MISSING_EMPLOYMENT_RATIO,
    COUNT_IF(PD IS NULL) AS MISSING_PD
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_RISK;
SELECT *
FROM CREDIT_RISK_MLOPS.REPORTING.DATA_QUALITY_MONITOR;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.REPORTING.RISK_MONITORING AS
SELECT
    CURRENT_TIMESTAMP() AS CHECK_TIME,
    RISK_BAND,
    COUNT(*) AS CUSTOMER_COUNT,
    ROUND(AVG(PD), 4) AS AVG_PD,
    ROUND(MIN(PD), 4) AS MIN_PD,
    ROUND(MAX(PD), 4) AS MAX_PD
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_RISK
GROUP BY RISK_BAND
ORDER BY
    CASE RISK_BAND
        WHEN 'LOW' THEN 1
        WHEN 'MEDIUM' THEN 2
        WHEN 'HIGH' THEN 3
        WHEN 'VERY_HIGH' THEN 4
    END;
SELECT *
FROM CREDIT_RISK_MLOPS.REPORTING.RISK_MONITORING
ORDER BY
    CASE RISK_BAND
        WHEN 'LOW' THEN 1
        WHEN 'MEDIUM' THEN 2
        WHEN 'HIGH' THEN 3
        WHEN 'VERY_HIGH' THEN 4
    END;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PD < 0) AS PD_BELOW_ZERO,
    COUNT_IF(PD > 1) AS PD_ABOVE_ONE,
    COUNT_IF(PD IS NULL) AS PD_NULL,
    COUNT_IF(RISK_BAND IS NULL) AS RISK_BAND_NULL
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_RISK;
SELECT
    'RAW.CREDIT_DATA' AS OBJECT_NAME,
    COUNT(*) AS ROW_COUNT
FROM CREDIT_RISK_MLOPS.RAW.CREDIT_DATA

UNION ALL

SELECT
    'FEATURES.CREDIT_FEATURES',
    COUNT(*)
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_FEATURES

UNION ALL

SELECT
    'ML.TRAIN_DATA',
    COUNT(*)
FROM CREDIT_RISK_MLOPS.ML.TRAIN_DATA

UNION ALL

SELECT
    'ML.TEST_DATA',
    COUNT(*)
FROM CREDIT_RISK_MLOPS.ML.TEST_DATA

UNION ALL

SELECT
    'INFERENCE.PRODUCTION_PREDICTIONS',
    COUNT(*)
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_PREDICTIONS

UNION ALL

SELECT
    'INFERENCE.PRODUCTION_RISK',
    COUNT(*)
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_RISK

UNION ALL

SELECT
    'REPORTING.RISK_SUMMARY',
    COUNT(*)
FROM CREDIT_RISK_MLOPS.REPORTING.RISK_SUMMARY

UNION ALL

SELECT
    'REPORTING.MODEL_SUMMARY',
    COUNT(*)
FROM CREDIT_RISK_MLOPS.REPORTING.MODEL_SUMMARY

UNION ALL

SELECT
    'REPORTING.DATA_QUALITY_MONITOR',
    COUNT(*)
FROM CREDIT_RISK_MLOPS.REPORTING.DATA_QUALITY_MONITOR

UNION ALL

SELECT
    'REPORTING.RISK_MONITORING',
    COUNT(*)
FROM CREDIT_RISK_MLOPS.REPORTING.RISK_MONITORING;
SHOW SNOWFLAKE.ML.CLASSIFICATION
IN SCHEMA CREDIT_RISK_MLOPS.ML;
CALL CREDIT_RISK_MLOPS.ML.CREDIT_RISK_BASELINE!SHOW_GLOBAL_EVALUATION_METRICS();
SELECT
    COUNT(*) AS TOTAL_PREDICTIONS,
    COUNT_IF(PREDICTION:class IS NULL) AS MISSING_CLASS,
    COUNT_IF(PREDICTION:probability:"1" IS NULL) AS MISSING_DEFAULT_PROBABILITY,
    COUNT_IF(PD IS NULL) AS MISSING_PD,
    COUNT_IF(RISK_BAND IS NULL) AS MISSING_RISK_BAND
FROM CREDIT_RISK_MLOPS.INFERENCE.PRODUCTION_RISK;
CREATE OR REPLACE TABLE CREDIT_RISK_MLOPS.REPORTING.FINAL_PROJECT_VALIDATION AS
SELECT
    CURRENT_TIMESTAMP() AS VALIDATION_TIME,
    32581 AS RAW_ROWS,
    25901 AS TRAIN_ROWS,
    6680 AS TEST_ROWS,
    6680 AS PRODUCTION_PREDICTIONS,
    6680 AS PRODUCTION_RISK_ROWS,
    0 AS MISSING_PD,
    0 AS INVALID_PD_VALUES,
    174 AS MISSING_EMPLOYMENT_TO_AGE,
    0.9553878904 AS ROC_AUC,
    0.9432925818 AS WEIGHTED_PRECISION,
    0.9402007857 AS WEIGHTED_RECALL,
    0.9369269504 AS WEIGHTED_F1,
    0.1784136403 AS LOG_LOSS,
    'SNOWFLAKE.ML.CLASSIFICATION SQL-native baseline' AS PRODUCTION_MODEL,
    'Pipeline validation passed; 174 records have missing EMPLOYMENT_TO_AGE and should be monitored.' AS VALIDATION_NOTE;
    SELECT *
FROM CREDIT_RISK_MLOPS.REPORTING.FINAL_PROJECT_VALIDATION;
SHOW TABLES IN SCHEMA CREDIT_RISK_MLOPS.REPORTING;
SHOW TABLES IN SCHEMA CREDIT_RISK_MLOPS.ML;
SHOW TABLES IN SCHEMA CREDIT_RISK_MLOPS.INFERENCE;
SELECT *
FROM CREDIT_RISK_MLOPS.REPORTING.RISK_SUMMARY;
SHOW TABLES IN SCHEMA CREDIT_RISK_MLOPS.REPORTING;
SELECT *
FROM CREDIT_RISK_MLOPS.FEATURES.CREDIT_FEATURES
LIMIT 10;